version: 0.0
os: linux
files:
  - source: app.jar
    destination: /opt/joget_app
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/chmod.sh
      timeout: 60
      runas: root
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: scripts/configure_apache.sh
      timeout: 300
      runas: root
    - location: scripts/configure_systemd.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: root