version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: salman123
      MYSQL_DATABASE: joget_db
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    command: ["java", "-jar", "app.jar"]
